#!/bin/bash

DEST=$HOME/local
LIB=$DEST/lib
INC=$DEST/include

SRC=$HOME/workspace/largenet/src
BIN=$HOME/workspace/largenet/Release

OBJ=liblargenet.so

cp $BIN/$OBJ $LIB

pushd $PWD
cd $SRC
find . -name *.h -exec cp --parents '{}' $INC \; 
popd

exit 0
